### ISSUE TITLE
[Request]: The Outcast sprx bf4

### ISSUE THREAD

**Issue by Jamessyt** [ohhsodead/arisen-studio-database#35]
### Mod Name

The Outcast sprx bf4 (the version the one you can see that the youtuber called mrjuliusmodz have.)

### Description

it is the version from this video: https://youtu.be/H3wvsuQM6T8?si=B29O0fZ1ZXD7NFc9
in exchange for this i can send the kurthax menu works without key brought back by my friend. which no has so far. only me and him.

### Game/Category Title

Battlefield 4

### What platform?

PlayStation 3

### System Type

- [ ] CEX
- [X] DEX
- [ ] HEN

### Created By

synful and kyle the salt

### Submitted By

jamessyt

### Game Region

bles01832

### Additional Context

![Screenshot 2024-03-02 133219](https://github.com/ohhsodead/arisen-studio-database/assets/161981903/45991f39-b232-413d-aa52-be7e16ab8bd1)

**Comment by ohhsodead** [comment]
> jamessyt

is this a paid version of the menu? we can discuss it more on discord if you like, either join my server or message me; ohhsodead

**Comment by ohhsodead** [comment]
trying to find more info about this and looks like its a paid mod, so cant be used with arisen but you can add it as a custom mod within arisen to still use on there
